### ISSUE TITLE
Bionic limbs can't be installed

### ISSUE THREAD

**Issue by kaptain-kavern** [skyarkhangel/Hardcore-SK#101]
[From here](https://ludeon.com/forums/index.php?topic=12996.msg251734#msg251734) : 

> I can't seem to install any bionic limbs. I've both advance medicine and regular medicine and both advance hospital bed as well as the regular 1. Not sure if it's a bug or I'm doing something wrongly.

link to @Jalordon PR : https://github.com/skyarkhangel/Hardcore-SK/pull/102

**Comment by Jalordon** [comment]
Bionics II seems to be required to allow bionic installation surgeries but it can't be researched because the prerequisites for Bionics II have a typo (Bionics II is the prerequisite instead of Bionics I , impossible to research). This is based on fixing the typo and seeing a bunch of recipes unlocked in the in-game help tab.

Personal opinion is that I'm not sure that research should be needed to install the parts, since traders can sell prosthetic parts that can't be used until the tech is acquired.

**Comment by kaptain-kavern** [comment]
Thanks.

link to @Jalordon PR : https://github.com/skyarkhangel/Hardcore-SK/pull/102
