### ISSUE TITLE
do raiders ever come?

### ISSUE THREAD

**Issue by awesome360** [skyarkhangel/Hardcore-SK#1025]
i was wondering do raiders ever comes like in day or the next day cause I always don't get them

**Comment by VorChar** [comment]
As of What I've heard if you aren't running one of the custom storyttellers you might get a lot less raids since vanilla ones aren't completely balanced for the modpack (more events for them to choose from).

I just finished poison ship, into raid into another raid in 2 days (on Cassandra too) so they obviously do happen

**Comment by awesome360** [comment]
and one issue I cant find the xm214 mircogun When I updated the modpack the gun isn't there anymore

**Comment by VorChar** [comment]
It might have been removed they changed Combat Realism to Combat Extended
