### ISSUE TITLE
current issues with newest version

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#150]
chitin head garment wont finish when it gets to 100% it wont finish. the pawn basicaly start and stops over and over.

people dont come back from events. sent 2 for a treasure hunt and 20 days later they still hadnt returned.

slate cobble stone flooring requires no stone but can still be built.

there still some flickering but not as bad as it was.  it does it a few times a min and is just the ui doing it not the game

**Comment by zakhad** [comment]
Reguarding your missing colonists/tribals You need to update Misc Incidents, manually as the github people haven't updated it,

The Github version of it is Version: 0.14.5 and the updated bugfixed version is Version: 0.14.6. The problem was with his CalcVerbValue as he was calculating how much firepower you are taking with you, and in my case the GreatBow had a stat that couldn't be calculated's he's made a workaround so it doesn't crash/loop, every time they're due to return (It'd just restart the timer)

**Comment by skyarkhangel** [comment]
Problems with craft already known, need to rework all apparel craft :/
