### ISSUE TITLE
Pawn just eating all strawberries until there are none available.

### ISSUE THREAD

**Issue by alkanna** [skyarkhangel/Hardcore-SK#1656]
Just this, doing nothing else than eating them. Job of the pawn was to collect edibles, whenever some strawberries are avbailable he eats them hahaha.

And yes his food bar is already full.

**Comment by BarikMorloc** [comment]
Haha ya I had this issue as well. Had 2 pawns eating all the fruit I harvested till it was all gone before they did something else.

**Comment by Alkanna** [comment]
Happened to me on new save, android mecanist scenario.

**Comment by BarikMorloc** [comment]
uga buga this glitch is annoying AF. But I think I know where its coming from sorta... It seems to happen to fruits when my tamer is collecting fruit to tame/train a animal. Instead of going to the animal with the 3 fruit he/she picks up the tamer will instead drop the fruit and it eat 1 at a time until all the fruit is gone.

Best way I have fixed this is by making a custom food restriction to not allow my tamer to eat fruits. This fixes it. This glitch started happening with the update when the loading screen was moved to the top of the load order... don't know if it's solely just with tamers or if someone collecting fruit to give to prisoner/patient will do the same thing. But as far as I can tell its only tamers when they are collecting fruit to train/tame animals.

**Comment by zachary-foster** [comment]
This happens when they are low on joy I think. They are trying to eat for fun, that's why it is always fruit and they eat even when full. Its annoying, but can be avoided by giving them joy activities I think.

**Comment by BarikMorloc** [comment]
> This happens when they are low on joy I think. They are trying to eat for fun, that's why it is always fruit and they eat even when full. Its annoying, but can be avoided by giving them joy activities I think.

It might be joy related. However, the only pawns that do it for me are those incharge of "Handling" animals. You are right that there joy is low but the other pawns don't do it, only the Handlers. Once you remove there Handling on there work tree they stop eating all the fruit. And once there is a better joy alternative to eating fruit they stop as well.

**Comment by masakitenchi** [comment]
Closed as too old
