### ISSUE TITLE
Fueled smithy work speeds

### ISSUE THREAD

**Issue by zakhad** [skyarkhangel/Hardcore-SK#169]
None of the none metal building materials that the fueled smithy can be built out of don't show how fast it'll work. Also why is tin so high at 120% workspeed? Tin has one of the lowest melting point temperatures at 231.9 °C The machine would literally melt before anything was crafted,

**Comment by Jalordon** [comment]
Modifiers for materials, including work speed, can be viewed in the ' i ' menu  when selecting material. Would be nice to have a table of material modifiers but I don't think it exists.

As for tin being really strong, I think that there needs to be a general review of material modifiers, as I agree it's really strong for how easily obtainable it is (Bronze which can be made of tin only has 110% and Alnico alloy has 115%).

**Comment by zakhad** [comment]
http://imgur.com/a/2GSrv

**Comment by Jalordon** [comment]
I think it doesn't display values that are 100% because it assumes that it's not important information. 

For example, some leathers like turkey and bear were not given stats like a lot of leathers were in the mod, so it doesn't list it.

The picture you gave showing slate block stats I think is also the case that nothing is defined to not be 100%, so theres no display of work speed,

**Comment by zakhad** [comment]
I had suspected that might have been the case, as you said with the leathers etc not showing for items at 100% Its very niche information not evereyone is aware of it, I've seen quite a few streamers always avoid building stuff out of materials (mainly beds) that didn't show immunity or operation info as they assumed it was 0 lol.

**Comment by skyarkhangel** [comment]
Answered by Jarlordon. Closed.
