### ISSUE TITLE
Diseases from mosquitos, fleas, flies are attached to a body part and not whole body

### ISSUE THREAD

**Issue by Jalordon** [skyarkhangel/Hardcore-SK#172]
Getting a disease from pests has the disease localized to a body part instead of whole body like diseases normally are.

If a pawn is lucky and the disease is in a non critical body part it can be removed to cure the disease.

**Comment by zakhad** [comment]
I've had quite a few in the ribs before lol, reminds me of dwarf fortress grappling mechanics, said dwarf grapples with his the goblin's left foot third toe via the right foot fifth toe.

**Comment by skyarkhangel** [comment]
its intended

**Comment by HelenB13** [comment]
I read that fleas can carry and transmit several potential illnesses of importance to humans, including typhus and plague, and can transmit infection with Bartonella among cats who can then spread the disease to humans. That's why I do my best to protect my cat and dog from fleas and ticks. usually, I buy Advantage Multi at Pet Pharmacy for them. Also, I know that in case something went wrong and you have a house full of fleas, there are special services that can help clean your home from these insects.
