### ISSUE TITLE
Impossible to save antibiotics from cats

### ISSUE THREAD

**Issue by l29ah** [skyarkhangel/Hardcore-SK#1933]
Cats try to consume antibiotics as food and get overdoses. If the tile with antibiotics and the tiles next to it are not included in their allowed zone, they will leave the zone and consume the antibiotics regardless. It's impossible to lock doors against tame animals.

Having both antibiotics and cats on the same base is unusable: cats need a pawn feeding them while overdosed, meanwhile they're quickly wasting precious antibiotics.

**Comment by sidfu** [comment]
not a bug its howw the base game does items.  there is no fix that wont break antibotics or other drugs that are needed to be given by a doctor

**Comment by l29ah** [comment]
I doubt that. In the vanilla game animals don't consume medicine, joints and alcohol, while you can still give those by a doctor.

**Comment by zakhad** [comment]
Pretty sure in vanilia animals can consume alcohol, beer comes to mind. But antibiotics is a modded drug item but in order for them to work in combination with medicines rather than a medicine itself they needed to be listed as a consumable so they were given a nutritional value. Antibiotics have a nutritional value of something like 0.001 so they will quite happily binge eat your entire stock until they black out or die if they happen to be nearby as it's the closest source of food.

I'm not certain if this will work, but you could try adding WM smarter food mod in the #patches channel in the discord adding antibiotics to ignore

WM smarter food selection\Defs\Compatibility\Core_SK.xml

<li>
     <def>MedicalDrink</def>
     <pref>Ignore</pref>
</li>		

Also the mod has better food prioritization for colonists and pets. wild animals still ofc won't care, and will consider the entire map for food rather than what's nearby.

**Comment by l29ah** [comment]
Okay, thanks. I wonder why isn't this mod included in Hardcore-SK.

**Comment by sidfu** [comment]
its not include as its easy to bug it and also it needs comp with alot of things to work well

**Comment by Pepelnica1488** [comment]
tynan 1000000 scum as is

**Comment by timegrinder** [comment]
While not an ideal fix, I found the food prioritsation (even with mods) wasn't perfect so did the following:

- Store medicines, alcohol, drugs etc in a specified area with a higher than normal priority (I used critical for the storage areas I used around the place, ie maybe a container in your medical bay)
- Set animals to only be permitted in specific areas (I can't recall if the animal areas are built in)
- Exclude the storage area (+1 square around it just to be safe) from the allowed area for the animals. Usually the area in / around your base, minus the tiles containing the consumables you want to keep them away from. If their area is 'whole map' there is the option to select the area you want to exclude and then 'invert selection' to select 'everything but that' on the map. (Again, I can't recall if this is in HardcoreSK by default or an added mod, sorry)

Overall I ended up with an area covering my base for pets / general animals that then just had some tiles / rooms excluded so they couldn't reach the medical / drug / etc stocks to eat them, (also did this for my fridge, for example). The area restrictions have always worked well for me, even sometimes to the detriment of the animals / colonists.
