### ISSUE TITLE
Potatos - New uses.

### ISSUE THREAD

**Issue by Vigilence** [skyarkhangel/Hardcore-SK#204]
I found it weird that there are really no uses for potato's early on.  This can be fixed by allowing potatos to be made into baked potato's and other recipes such as french fries etc.

![bakedpotatowithbutter](https://cloud.githubusercontent.com/assets/16742086/18152765/6808cad8-6fc6-11e6-8801-954d607b7487.jpg)

**Comment by harchschoolboy** [comment]
I found it weird that you can't plant potato with potato. 

Vigilence, i'll try to make baked potato today.

**Comment by harchschoolboy** [comment]
I'll make it as patch in a few minutes. But probably it require rebalance to decrease it's nutrition

![image](https://cloud.githubusercontent.com/assets/3436744/18163554/38e3ed5e-7044-11e6-9bc9-590fcc803c16.png)

**Comment by harchschoolboy** [comment]
#207  
:3

**Comment by jnkyacc** [comment]
:O it quite huge potato

**Comment by harchschoolboy** [comment]
I've used image from op post to create texture)

**Comment by zakhad** [comment]
You do something like this then, it imbalances every other food crop, why not roasted carrots? Tomato soup? Stuffed eggplant? etc

**Comment by harchschoolboy** [comment]
I have an idea to expand low-tier recipes list to make vegetables more useful to grow
Soups, fried everything and stuff

This one was created for fun, as resolution for this certain issue

**Comment by Vigilence** [comment]
Wow nice harchschoolboy.  

Zakhad those ideas sound great.

**Comment by zakhad** [comment]
@Vigilence  I was being sarcastic. But sure if you want to make a mod go for it, my worry is that you'll start overwhelming the whole food system with 20-30 new recipes for each food and you can only list so many on 1 machine its why assorted veg worked albeit terrible but it was a good early game starter that worked on many a veg.

**Comment by harchschoolboy** [comment]
I'm not really sure that we need extra detailed meals, like 10 types of soups, or 15 types of salads, it can be meat salad, veggie salad, some fish salad for example, same with soups
because micromanagment is able to kill fun

so when i get any plan, i'll create issue

**Comment by Vigilence** [comment]
Take a look at star dew valley.  They grow essentially the same crops and actually have recipes for them with buffs.  Now that would be nice for this game too.  We don't need 50 recipes for 1 crop, but they should stand alone and not be useless filler items.

Starting at neolithic and only eating meat and meat and meat with no other options kinda sucks, so that's why I suggested baked potato's as they are useless by themselves which is bad.

**Comment by Jalordon** [comment]
Personal opinion is that current meals need to be reviewed for what they are supposed to do and their costs.

 I like having a variety of food items but they also should each have a purpose to justify having more meal types (possible things being more joy, a hediff/effect, longer spoil time or some bonuses as Vigilence said). 

Vanilla had just simple/fine/lavish and it was wanting for expansion, but I feel like I still just make only simple and fine meals when I can since there really isn't any significant advantage to making anything else.

A few examples of issues that I see with meal choices now:

- Burgers cost 10 meat and 1 bread (0.7 as roasted meat and 0.4 eating the bread) for a 0.65 meal. Other burgers/sandwiches are overall a bad idea to make because too much cost for little gain.
- Fried assorts cost as much as simple meals (8 basic foods) but give 0.45 nutrition to the 0.85 of a simple meal, practically only exists to give a crappy way to process potatos or other crops when only the grill is available. Pot roast with mushrooms feeling like the same but with fine meals.
- Mushroom meals don't look particularly worth the effort of trying to get mushrooms to make them, since they feel the same as the generic meals which can also use mushrooms.
- Jerky feels crazy good that its 0.1 nutrition less at the same cost as roasted meat. but lasts two seasons. I make a few roasted meats for marginal efficiency gains but I feel that I could get away with making only jerky. I know you need early game long term food solutions to cut down on tedium focusing on food but still feels really good.

I probably missed a few other things that stood out but the overall thing is that It doesn't feel like there is that much reason to make anything but the generic meals.

**Comment by jnkyacc** [comment]
@Jalordon it's huge amount of work to balance all food and no free hands. Still fixing A13 bugs and here already A15... So suggestions always welcome :)
