### ISSUE TITLE
Various bugs

### ISSUE THREAD

**Issue by Leslac** [skyarkhangel/Hardcore-SK#2059]
Hi guys, love your modpack, it's really the way Rimworld should be played.

 I've noticed a couple of bugs that you might be able to do something about.

 The Terraforming mod that allows you to turn ice to shallow water apparently makes naturally formed ice turn into shallow water everywhere. So when you play in a cold biome you get shallow water everywhere after a cold spell... Basically a fifth of my map ended up flooded.
 Oddly enough, I can't find what mod allows you to do the terraforming (it seems like it's Fertile Fields, but I don't see that in your mod list), but I think there may be some unforeseen effect between NPS_SK (Nature's Pretty Sweet) and the terraform mod.

 The version of Hospitality you're using has a bug that was fixed in a newer version. Basically the bug is guests have an unreachable rallying point and immediately leave the map after arriving. The only way to fix it currently, is to start a new game and just hope the bug doesn't happen again. So you really should update your version of Hospitality to a newer version where the bug's been fixed.

 I've gotten a cascade of bugs with Tools Matter and abandoned a game because of it. Right click menu no longer works... I don't know the cause of this, but I suggest you update your version in the modpack to a newer version of Tools Matter, as it may be a bug they've fixed.

 Cheers for all your great work!

**Comment by zakhad** [comment]
Hey.

Are you playing on the development or master branch - if dev branch when did you download it?

The NPS i believe is a known problem where marshes and marshy soils are classed as 'water' tiles and anything with the 'water' tile tag gets turned into ice but doesn't remember what it's previous tile was, i'm not sure if that was intentionally left as its due to memory limitations back in B18, but it could be relooked at by Sky.

The Hospitality, most likely does need to be updated as you've stated, depending on what version of the pack your running with.  it's been advocated in the discord, at least on the english one by myself and sid that people use the steam workshop version of it since it's always up to date and we make no alterations to the mod. 

Tool's matter? "SurvivalTools_SK?"? Can you show screenshot on the dev console highlighting the red error when it happens and expanding the description box of that error? Or post the output log please, While i doubt i can fix that one no doubt sky or sid might know what's going on, this is the first i'm hearing about this problem.

**Comment by Leslac** [comment]
I'm on the dev branch, latest update. I think the game I was playing had been started like six months ago or thereabouts.

 I'll get back to you with the screenshot. The game was pretty borked, so I dropped it. Hospitality didn't work at all, even after updating to the most recent version (I waited for some guests to come by and saw them leave immediately) and I had to turn off Survivaltools (not "tools matter" yeah) to even be able to right click anything.

**Comment by zakhad** [comment]
Regarding hospitality did you have your main entrance locked via locks mod? Can u delete and replace the doors to rule that out, as I've had guests visit and leave but that was because i had a locked drontdoor as it were.


You say you started your game 6 months ago and have the latest dev?  You've been updating through Combat extended 1.4 to 1.9 then? That required a new game at that update, im fairly sure survival tools had a similar update fixing that right click bug; might be related to the CE update tbh. 

I assume your able to start a new game without any problems? I highly doubt we can salvage a save game that updated post a new game required update. The development branch has been known to break save compatibility unfortunately when you update your game; also how are you updating - whats your process?

**Comment by Leslac** [comment]
At least 6 months, maybe more, following the updates throughout. No worries about salvaging it, just wanted to let you know about some of the bugs I've encountered. I can run the save if I disable the tools mod.

 I've had no locked doors between map border and the guest room. But as I said in Discord, there's a chain on the Hospitality mod Steam page about a similar bug, which the creator fixed in one of his later updates. When I had the bug I had a look at the Hospitality mod folder and noticed that it was a version from before the bug had been fixed. That was about a month ago, so dunno if it's been fixed in the meantime.

**Comment by Leslac** [comment]
And yeah, the new game is working without issues. Just the really annoying flooding everywhere (because I'm on a arctic forest biome spawn). I'll check the original mod whether it's something he's done anything about.

**Comment by zakhad** [comment]
No we have a unique modified version of nps and it's very different. You're refering to the tiles i mentioned, biome doesn't matter and is irrelevant. Its the tile types.

Using the launcher to update is unfortunately only for people that are truly unfamiliar with modding, its a flawed system. It's great for the first install and replacing files but it tends to break your install after a few weeks of updates, idk how it updates tbh but i know it doesn't delete files it just downloads new and replaces existing files, any old leftover files can and usually cause weird bugs. Delete your install and do a fresh install via the launcher with a fresh 1.0 untouched vanilla game, so that there r no leftover files.

**Comment by Leslac** [comment]
Ok, good to know.

 Concerning the biome, the problem is with ice tiles, so the colder the biome the more ice you get, the more your map will flood. I didn't have this problem at all in a warmer biome, so it's really an issue that will only happen in some cases.

**Comment by zakhad** [comment]
I'm not understanding this flooding all "water" classed tile will turn into ice i.e swamp/marsh tiles they do not remember their previous type (due to the old 3.6gb memory limitation of B18 it used too much memory back then) i.e marsh when they get frozen into ice - when they defrost they turn into regular water. This is what your refering too? Which is why your map looks like it's flooding? Or are you refering to something else?

**Comment by zakhad** [comment]
Ice defrosts/freezes maps that start with them that are too warm will effectively make your map appear to flood but that's intended, ice defrosts into water it's not intended to stay ice if it's too warm?

**Comment by Leslac** [comment]
I have both shallow and deep water where there used to be sand, dirt, soil, marshy soil etc. After enough snow falls, the tiles turns to ice and when the ice thaws it turns everything into water tiles. So now I have lakes everywhere. Also the ocean has taken over a lot of the coastline, making a weird dotted mix of water and sand.

 Whether it only does it to marshy soil and marsh, I can't say, but it seems to be pretty indiscriminate.

 As I said, about a fifth of the map (not counting mountains and cliffs), has been flooded with shallow and deep water. Which seems extreme...

**Comment by Leslac** [comment]
I can send you my save if you want to see it for yourself...

**Comment by sidfu** [comment]
if u are using a old save thats the issue. U CANT use any old game for the new CE/oil/ nuclear changes.

your issue is that your save is bad now so data is failing to save correctly. the bug with swamps turning into wat4er is a old bug that should only happen when the game has bad data in the save. 

the only tiles that can flood are costal ones for tides and river deposits that it places along rivers and lakes

**Comment by zakhad** [comment]
So the problem is when regardless of the tiletype (Does this happen with constructed tile i,e stone slabs?) The snow is now a valid target for turning into ice? I didn't/wasn't aware that was a thing so it's not what the tile underneath is the problem it's the snow turning into ice and subsequently turning into water, that's really strange as other people would have reported such a glaring problem by now.

But I am suspecting it is what sid is saying in that your game can't save your data properly due to the update and it's resetting or defaulting the saved data.

If this isn't repeatable via a new game with a "clean" install then it's definitely a update issue that corrupted your game, as I've not heard anyone mention that they've large swaths of there map to flooding. 

The only issue that can be addressed here is the hospitality requiring a update.

**Comment by Leslac** [comment]
It's a new game, new save. I'm not seeing it change any constructed tiles (since it's a new game, I only have ruins to go by).

 I can try a new game with a clean install and will get back to you in a couple of days as the game needs a season or two to pass before the water has taken over.
