### ISSUE TITLE
Jerkey and Roast Meat cost too much

### ISSUE THREAD

**Issue by ghost** [skyarkhangel/Hardcore-SK#241]
It takes 10 pieces of meat to convert to 1 piece of jerky or 1 piece of roasted meat.  That is incredibly high, especially considering how long it takes to cook that meat and the amount of times they are eaten per day.

It renders a full sized muffalo to a few measly pieces of jerky, which doesn't make sense for an animal of this size.

I always thought that 1 peice of meat would convert to 1 piece of jerky or roasted meat but 10:1 is ridiculous.  

With the imbalance of crops, You will wipe the entire map of animals just to feed your guys for a few days.  I have wiped the entire map of animals during winter plenty of times because of this.

![screenshot 62](https://cloud.githubusercontent.com/assets/16742086/18295609/d960f8aa-7470-11e6-8a24-9eec71b0a3dc.png)
![screenshot 63](https://cloud.githubusercontent.com/assets/16742086/18295610/d960ecfc-7470-11e6-9e14-2ca63d36d92d.png)

**Comment by jnkyacc** [comment]
Compare nutrition.
Can be closed.

**Comment by ochkoebanoe** [comment]
It is enough to feed 7+ pawns. After this you can build merchant spawner and buy seeds.

**Comment by Jalordon** [comment]
To put in perspective in vanilla you'd get a simple meal (0.85) that can be made from 10 meat (the same in this case). I think of it as roasted meat is lower quality (0.7 nutrition, 3 day spoil time instead of 4)/early game food that is justifiably worse because you need less tech to create it. Jerky being like 30 days spoil time for 0.6 nutrition, well worth the tiny loss of nutrition if you have no freezer tech.

I probably restated what the others said before but this shouldn't be an issue.
