### ISSUE TITLE
Earthquake in the space(incompatible with SOS2)

### ISSUE THREAD

**Issue by slyhw4** [skyarkhangel/Hardcore-SK#3355]
I tried to decompile the Core_sk.dll and found it might be the following code in GameCondition_SeismicActivity that cause the problem:
    public Map target => Find.AnyPlayerHomeMap;
Should it be current map or something like in other game condition?

**Comment by zakhad** [comment]
![image](https://user-images.githubusercontent.com/5264667/172508525-0bf22a2a-daed-4c55-a170-9c698f789c04.png)
While not a direct answer but a alternative solution to the question/problem could be in that you could stop the event entirely via incident tweaker mod and or other events that shouldn't happen in space. 

Ye know space tornado's are !!fun!! or whose to say the gravity generator malfunctions that would otherwise play as if you had a disruption akin to an earthquake where it keeps pulling gravity in weird directions smashing/destroying various objects in the ship. 

I'm not trying to belittle your question, if i knew i would answer so i can only offer the aforementioned alternative solution which might be enough or not.
