### ISSUE TITLE
О коронавирусе.

### ISSUE THREAD

**Issue by SetAriman** [skyarkhangel/Hardcore-SK#3425]
Можно ли уменьшить заражаемость? Он очень быстро выводит из строя колонию. Заболевает колониста 4 и песец. Даже с учётом того, что я заранее купил и поставил в госпиталь уборочного бота. Коронавирус часто спавнится. Больных надо часто лечить, кормить и прочее. И зачастую вирус спавнится прямо у врачей под ногами, с высоким шансом сразу же заражая ещё и их. А лечение долгое, даже с трофейными красными аптечками. В результате или сейв-лоад, или колония под угрозой. И это ещё ни кто не напал. Иначе пришлось бы поднимать больных в помощь и моментально вирусом забило бы всю колонию.

**Comment by SergeyPomelov** [comment]
Я бы вообще выпилил из дефолта коммуникейбл десиас пока не будет сделаны механики позволяющая создавать нормальный карантин и иммунитет (не обязательно вечные 100% для всех болезней, но иммунитет блин, а не так что простуда может вечно гулять по небольшому поселению, это основное в модели инфекционных болезней). Он банально недоделан, неиграбелен и неинтересен, сделано только самое простое. По факту тупо микроменеджмент уборки и карантина или смертельный приговор от супер частого ковида в зависимости от того какие техи используешь. Про болезни животных вообще молчу, там микрить в квадрате, по сути всегда тупо валишь заболевших, даже если там бондед.

**Comment by Zim777** [comment]
Просто зайти в настройки мода и поставить распространение на 0 - не судьба?

**Comment by SergeyPomelov** [comment]
Так и делаю каждый раз. Это не повод держать моды которые отключают 95% для количества.

**Comment by SergeyPomelov** [comment]
Я люблю этих ботов, пишешь куда-то репорт, а потом защищай ишью своим телом. По моему бот должен ебашить письмами ответственного, пока он глазами не посмотрит или не признает что он больше не саппортит этот компонент, а такая дефолтная фигня просто заметает под ковёр и говорит всем что репортить баги в этот репозиторий не нужно. Тут ещё ладно - просто балансовая вкусовщина, но на всякие баги которые пользователь старался воспроизводил и расписывал такая же политика.

**Comment by TheLoneTec** [comment]
This is not the place for Feedback honestly. The discord is better for this, there is a specific place in the discord for feedback like this. Github issues are for Bugs/major issues that have actually been investigated and information has been provided. The reason most issues here go unanswered is because they are seen and most of them are deemed not important or relevant enough for attention. Whenever someone posts an issue here, it is shown in the discord, if someone on the team felt like it was an issue taht needs to be addressed, they would address it.

**Comment by SergeyPomelov** [comment]
@TheLoneTec This isn't how it should be organized. While it's none of my business, it is within my area of expertise. Just saying, there should be codebase part owners who handle the triage. They should decide the validity, importance, and priority of the reports, not just an amount or loudness of users' pain screams. Kudos for the attention to the comment.

**Comment by TheLoneTec** [comment]
and even then, its not a gaurentee

**Comment by TheLoneTec** [comment]
Discord is something i check my phone for regularly. Github is not. Github is something i only check when im forced to do something.

**Comment by TheLoneTec** [comment]
Something that people can do, if they really want to post here, is also make a post in discord linking to the github issue. Its honestly the only way its gonna get seen and addressed.

**Comment by SergeyPomelov** [comment]
@TheLoneTec Great, I have joined the Discord channel and will post new issues there. No, I am not that insane; I am aware that HSK isn't a commercial project. A code owners system is suitable for any open source project, even if there is only one owner. Also, it is much more expected by bystanders that GitHub or JIRA, not Discord, is the primary issue tracker. If there is no a clear owner of a code, the component is deemed partially or not supported. However, that isn't a shameful brand since the support is a voluntary action for the community, not an obligation — mere an expectations hint for other code/repo users.

**Comment by TheLoneTec** [comment]
I understand. Was just trying to help explain the current situation of the project. Its....complicated. I just know from personal experience over the years, this is what ends up happening with Github Issues for this project. Not much can be done about that.
