### ISSUE TITLE
Disease Incident

### ISSUE THREAD

**Issue by trevize23** [skyarkhangel/Hardcore-SK#343]
Hello, I suggest tweaking the flu/plague/malaria events. Not sure if I just got very unlucky but in the last 2 games I played my colony was almost constantly sick from the second year onwards. Considering that you can't do anything against the event (?) and that it takes down around half of your colony for quite some time it feels more like needless punishing than challenging. 

![disease events](https://cloud.githubusercontent.com/assets/22052564/18670931/618f031c-7f42-11e6-8b9d-295da6a5fa1b.jpg)

**Comment by Mongoon** [comment]
I may be wrong but diseases are not THAT often (at least i didn't encounter them so much). Easiest way to contract them is by fleas or mosqitos, so if you have any in your home area and people have contact with them, that is your problem. Kill them and enjoy healthier time.

**Comment by Inei** [comment]
Except fleas and mosquitoes - every biome has a certain chance (you can see it in help section for each biome in game), for colonists to contract biome-specific disease each year. The chance is quite low, but for some reason game fires it simultaneously for all colonists at once, which makes it quite odd. I mean it is fine if some colonists can contract some disease during the year, especially in hot climate biomes, but somehow it turns out like 20-40% of colonists become instantly ill at the same time from the same disease, and on the same stage. It would be nicer if colonist could contract disease, and then, feel bad and so, and you'll have to do medical examination of that colonist to check what's wrong with its health, and to quarantine it, so disease won't spread to other and such. Though, I believe something like this will be implemented in future versions.

**Comment by trevize23** [comment]
Yeah it's from an event like Inei described. I'm playing in the 2nd (or maybe 3rd) coldest biome and you can see in the picture that my colony has been hit two times in a row. I lost all will to keep playing considering that plague pretty much kills 100% unless you have a medical bed.

**Comment by Inei** [comment]
Plague is not so bad, just try to make bed with best immunity gain factor. It is taken from material the bed is made. Hemp and feathered raptor leather will do nicely for that, making colonists stay fed, and being in bed will greatly increase immunity gaining speed. You can check current character immunity gaining speed and factors that important for it in character sheet.

**Comment by trevize23** [comment]
Yeah I know that some materials give better immunity gain. Sometimes you can't get those fast enough and other times you won't even be able to trade for them (my last 3 traders left instantly because it was too cold). Sometimes you just have bad luck. I just don't think almost half my colony being useless for ~2 seasons so early on is a good mechanic. 

Anyways this wasn't about Plague, but the disease incidents happening right after each other. Maybe add some cool down (like raids) for it.

**Comment by trevize23** [comment]
3rd start:  boreal forest; half my colony got plague during first year (day 15). haha such fun.

**Comment by skyarkhangel** [comment]
Works like in vanilla.  In a13-a14, Tynan make changes in Disease Incidents.
