### ISSUE TITLE
Visitors dying of hypothermia 

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#367]
Visitors will buy lots of things from you for their 100 or so sliver ore, but then they walk so slowly that they die of hypothermia if it is a little bit cold out, angering their faction. 

Sometimes, they die of hypothermia even if you don't sell them anything. 

This is annoying because you have no control over the clothes they come with, other then selling them warm clothes there is nothing you can do :(

**Comment by ScottS9999** [comment]
I have had visitors leave because it was too cold, but it shows an obvious placeholder message like "VistorsLeavingTooColdMessage."

I know this is out of scope at the moment, but I believe the intent is to include crashlanding into the mod pack at some point, so it may be relevant in the future.  Traders and visitors also do not avoid reactor crash sites, and they eventually die of radiation poisoning.  I think a general environmental danger avoidance behavior needs to be included.

**Comment by skyarkhangel** [comment]
its vanilla "feature". Rimworld raid generator since a14 have nasty bool "desperate". When the game considers that need Raid to your colony at any cost, start to ignoring main generator rules, like temperature and time for early faction. Tynan going crazy.

**Comment by skyarkhangel** [comment]
Reworked vanilla raid generator. Plz, test.
