### ISSUE TITLE
Баг RW 1.4: пешки, не назначенные на перенос не могут выполнить работу основной профессии

### ISSUE THREAD

**Issue by Shahimat** [skyarkhangel/Hardcore-SK#3708]
Всем привет!)
Посмотрите пожалуйста ситуацию по следующему багу (самая последняя dev версия 1.4):
Пешка умеет строить, но не умеет переносить. Как выяснилось, сейчас пешка из-за этой особенности не может строить
![image](https://github.com/skyarkhangel/Hardcore-SK/assets/50878292/d7162614-f4b1-433f-b9e9-d76f721ddb05)
Здесь показано, как я пытаюсь прокликать правой кнопкой указанной пешкой по проекту стены - никакой реакции(
Ограничений на зоны нет
Выяснил связь с переносом следующим образом: на скрине выше есть вторая перша, которая назначена надзирать, ситуация такая-же - нажатие правой кнопкой по пленнику - не работает(
Спасибо!)

**Comment by Shahimat** [comment]
![image](https://github.com/skyarkhangel/Hardcore-SK/assets/50878292/823dff17-b728-4ed2-a8b5-800a303939ee)
![image](https://github.com/skyarkhangel/Hardcore-SK/assets/50878292/a0dc5825-1941-44ef-b572-2651e65dbb74)
На всякий случай прикладываю скрины версий, а также список используемых модов (немного отличен от дефолтного)
[list_of_using_mods.txt](https://github.com/skyarkhangel/Hardcore-SK/files/12043503/list_of_using_mods.txt)

**Comment by TheLoneTec** [comment]
please post a bug report on the discord, wiht your Hugslib log.

**Comment by Shahimat** [comment]
log link is:
https://gist.github.com/HugsLibRecordKeeper/e69d1a443d15d7f4a99a4997dcef9bd6

**Comment by TheLoneTec** [comment]
#Bug-Reporting https://discord.com/channels/272340793174392832/1067871456328958002

**Comment by TheLoneTec** [comment]
ok first off, correct your load order, the last bit is wrong, the last 5 mods from the default load order must always be last. Secondly, because of the Survival Tools update, you need to delete all existing tools and spawn them back in via Character Editor. And finally, it seems your save has some hash errors, so Download "Mid-Save Saver" and use its "uncompressed save" option, follow its instruction on how to do it via its tool tip in its mod options.
