### ISSUE TITLE
list of current found issues

### ISSUE THREAD

**Issue by sidfu** [skyarkhangel/Hardcore-SK#384]
1. campfires--provide no light or heat. haulers wont refuel them unless there 0 haul jobs and then 
                     they still at times ignore 
                       them.
2.   building campfire in prison area. causes a error when decon that can crash your game as  it repeat 
      so much. 1sec=500+ repeats of error
3.  ~~tin ore---- for some reason tin ore has a burn rating so haulers will use it.~~ seems to be
        somewhat fixed but still has burn info.
4.  burn fuel----- haulers chose best burn material at times instead of closest
5.  algae--- when used in permicain causes a bug about amount and defaults to 1.

 that's all i see so far with the newest git ill update as i see more.
 [output_log2.txt](https://github.com/skyarkhangel/Hardcore-SK/files/504441/output_log2.txt)
 [output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/504442/output_log.txt)

 (ignore errors at start of one about bad map as was trying to load old save to get map name again :P)

new items.  build just prior to 7574fc6

6.---refueling priorty. hauling a dead animal, refueling a torch, hauling coal from other side of
the  map are all more imporant that reufeling the crucial coal heater and fuel stove :P
7.----glowstone research error Could not resolve cross-reference to Verse.ResearchProjectDef named SK_GlowstoneLamp

**should be easier for u to read now :P**

**Comment by jnkyacc** [comment]
@sidfu 
1.2) ignoring only campfires or other refuelable stuff also?
1.3) possible some issue with prison zone area
2) should be fixed in #385 
4ram) Try increase virtual memory

output_log.txt - campfire glitch. Try delete it from your save file
output_log2.txt - Try increase virtual memory. And make sure that you dont have HighRes surfaces/Surfaces folder. From github you need only "Mods" folder.

@skyarkhangel 
На кривой фильтр видел уже много жалоб что иногда тащит доски которых в списке нет. Если в фильтре разрешить все и сохранить, то в сейв оно пишет абсолютно все айтемы игры.

**Comment by sidfu** [comment]
well on the campfires they will keep hauling everything else and never touch til they last. but i found something if u put them in combat mode then move them right next to the campfire and uncombat them they instaly go to fuel it so maybe something is interferring with the range for it? that might be while the fires dont make any heat.

**Comment by skyarkhangel** [comment]
Поковырялся в исходниках. Кажется нашел как сделать нормальный фильтр. Буду пробовать.
