### ISSUE TITLE
Cold snap kills crops even if temperature never gets too low.

### ISSUE THREAD

**Issue by Rufert** [skyarkhangel/Hardcore-SK#400]
Had a cold snap in a tropical rainforest, temperature never went lower than 20c, yet all my crops died anyway.

**Comment by zakhad** [comment]
1 Possible answer is that: they can die of old age so to speak, if they're really slow to grow to 100%  maturity as each seed has a life expectancy.

Example Def:

				<thing Class="Plant">
					<def>PlantTreePine</def>
					<id>PlantTreePine153129</id>
					<pos>(18, 0, 230)</pos>
					<health>300</health>
					<growth>0.3250679</growth>
					<age>1256000</age>                                <------
					<unlitTicks>36000</unlitTicks>
				</thing>

**Comment by Rufert** [comment]
Ain't what happened son. Pretty much everything on the map except trees died within three days after the cold snap started. Had potatos of various maturity levels.
I think the snap is just scripted to kill crops. It was that weird storyteller with lots of events and less raids, I don't think the cold snap was even supposed to occur in the biome I was playing in.

**Comment by Mongoon** [comment]
I'll give it a shot. Plants die only if they have reason, so i guess the temperature DID get lower than 0, but you checked temperature inside your base, not outside.

**Comment by Rufert** [comment]
The temperature is always 27c inside my base on account of it being inside a mountain. Potatos were outside, but I kept an eye on the temperature. It was in the middle of summer, the lowest it got outside one night was 11c. But everything still died, all my potatos, haygrass, and even the natural grass all over the level.

**Comment by Dunkhan** [comment]
I had a similar issue: after the cold snap was over the farm plots all still said it was too cold to replant the crops. This didn't seem to be going away. I tried reloading the save and it was unable to load, with the message 

Map -1 couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings

This is a message from the unity engine.
I have had this unable to load issue once before in this version, but it was unrelated to cold snaps

**Comment by Dunkhan** [comment]
Ok I just loaded the previous save, where the cold snap was still in progress. This save repeated the problem with the farm plots, and when I saved and loaded the map failed to load again.

Sucks for me because now I have to load an even earlier save and lose even more progress.

Good for the devs though, as it means this bug can be reproduced at will. 
To reproduce the symptoms I am getting with the attached save game:

1. Load the game
2. Wait until the cold snap ends
3. Observe that nothing can be planted on the farm plots
4. Save the game
5. Load the game
6. Observe that the load process hangs forever, and that and endlessly repeating message is in the log file.

I apologise that my game is not up to date with the current version, it is about 3 weeks old.
If the save can not be loaded in the current version I can zip and send my whole game folder if needed, please let me know.
[Autosave-2.zip](https://github.com/skyarkhangel/Hardcore-SK/files/809231/Autosave-2.zip)

**Comment by Dunkhan** [comment]
Confirmed this in a much newer version. Let me know if I should upload another save.

In the current version the saves can be loaded so steps 4-6 of the reproduction above are no longer relevant
