### ISSUE TITLE
Smelt copper - requires coal?

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#407]
Is it intentional that smelting copper requires coal?  It makes sense that steel requires coal, tin and many others already do not require coal.  I would think that copper should not require coal.

**Comment by nemesis688** [comment]
I think it's because of the furnace you are using. The early ones need a fuel source in order to work but once you get to electric the coal requirement for copper is no longer there.

I think it might be an oversight since the fuel system addition.

**Comment by skyarkhangel** [comment]
Issue author right. 
Recipes with smelting need to update, since new refuel system.

**Comment by zakhad** [comment]
I wasn't sure about this either, whether or not the fuel used in smelting was part of the actual furnace or outside of it, it seemed a bit weird to use both imo with the exception of steel. 

Was tin intentionally not requiring coal due to extremely low melting point temperature of around 232c when say compared to copper which melts at around 1083c?

**Comment by ScottS9999** [comment]
My recommendation:

The new fuel system handles the material that provides the heat necessary for the reaction.

Iron requires the addition of carbon to make steel, so it makes sense that the steel reaction would require additional coal.

Copper, tin, etc smelting does not require the addition of carbon (as far as I know, I'm not an expert), so those reactions should not require additional coal.

**Comment by skyarkhangel** [comment]
Fixed
