### ISSUE TITLE
Colonist shot himself?

### ISSUE THREAD

**Issue by ScottS9999** [skyarkhangel/Hardcore-SK#458]
Colonist was attacking an animal.  The animal moved through the tile where the colonist was, and the colonist ended up with a bullet wound to the heart.  Not cool.

**Comment by LimeCookies** [comment]
To be honest, I don't think there's any need to 'fix' that. Guns aren't supposed to use in close range IRL. It's not impossible to shot your foot in real life.

**Comment by ScottS9999** [comment]
Not impossible, but it requires an astounding amount of fail to shoot yourself in the foot, much less in the heart,

**Comment by zakhad** [comment]
Honestly I think if you try to shoot someone in melee it needs to have a small chance to shoot yourself, or lose your weapon depending on the vs melee skill, would be really interesting not sure how the hell it would be implemented though lol.

**Comment by ScottS9999** [comment]
Speaking of which, I think the heart should have fewer hp.  A wound that penetrates to the heart and does any damage at all is pretty much guaranteed to lead to a quick death.  This guy got a bullet wound to the heart, and still walked half way across the map to get stitched up.

**Comment by zakhad** [comment]
Idd but it would make terrible gameplay, bad RNG heart shot would make a lot of people ragequit. A compromise perhaps? Massive bleedout like 500% so it would go up like  5% a second rather than outright kill you, so you might just be able to save someone with an emergency floor bed if you have a half decent medic granted it'll be so rare that you'll ever get the chance to save them in the middle of a fight but, a chance is better than no chance e.g. bad RNG

**Comment by ScottS9999** [comment]
CR is supposed to be realistic, right?  I would argue that if you don't want the possibility of a one-shot kill on a human, either wear armor or don't play CR.  That's said, I like your idea about a quick bleed out rather than insta-kill.
