### ISSUE TITLE
strange FPS drop in mid game

### ISSUE THREAD

**Issue by m3nda** [skyarkhangel/Hardcore-SK#501]
Version: 4.2.1
Branch: master
biome: ice sheet
storyteller: rey
diff: rough
colony progress: mid-game (4 year in game)

After ~30 minut of game (after load, not new colony) FPS starts droping, save-load not helps, restart of game helps for next ~30 minut.

savefile: [Ice Village.zip](https://github.com/skyarkhangel/Hardcore-SK/files/679575/Ice.Village.zip)

**Comment by zakhad** [comment]
When you enable dev mode do you get console spam associated with psychology mod saying something about anxiety?  I had something similar to this and by updating the mod has been reported to fix this issue for myself included prior to actually using the modpack, I had this happen after a certain update to psychology. 

The symptoms that I experienced were that it would literally drag the fps down when the anxiety hediff event happens. but would go away after a while but it will re-occur every now and again due to a broken mechanic. (I don't technically know what's wrong)

Sky also recommended that people not use the mod until its been proven stable so unless you start over, or find a way of doing edits to your save/pawns to remove the psychology anxiety manually it's going to keep happening I'm afraid, **This is only if its the same issue I think it is,** it would help if you posted a enabled dev mode console output (Screenshot) when the lag is happening, also if you could post an output_log, a little description of what you were doing up to that point.

(You could also kill the pawn who has the anxiety via dev mod if you really want to carry on but n ot fussed about losing the pawn and also disabling the mod)

**Comment by m3nda** [comment]
Output log: [output_log - copy.zip](https://github.com/skyarkhangel/Hardcore-SK/files/680798/output_log.-.copy.zip)

Log writen when fps drop started. I noticed that also raids generates fps drop, which is keeping even after end of the raid.

@zakhad 
i don't know if its psychology, but i didn't noticed any relation between moods and fps drops
