### ISSUE TITLE
Why aren't the Rimsenal Weapons in Hardcore SK?

### ISSUE THREAD

**Issue by SmokeyUnicycle** [skyarkhangel/Hardcore-SK#543]
The storytellers and Feathered Raptors are included but the several weapon packs are not,  3 to 5 sets of futuristic weaponry would do a whole lot to make the late game more interesting. 

Right now there are not many high tech weapons and a very large number of modern day firearms. 

These are a bunch of very high quality diverse weapon sets from an author already contributing to Hardcore SK that would fill a small hole in the Hardcore SK's options. 

It would also be a great opportunity to use the many types of in game resource in Hardcore SK, with each weapon set using different alloy ingredients. 

https://docs.google.com/document/d/1WUAjRYfXyT-Gz-xD3eth56UbzZ--S8HdtK782jFnKqw/edit

There are also the Federation and Ferals packs. 

----

I'm guessing you could probably get permission since you're already using some of his stuff

Then you'd just need to tweak the weapons for Combat Realism (using the six future ammo types already in game or maybe add a new ammo type, just recolor the existing graphics?) and then crafting and research for them. 

Sorry if I'm missing something obvious, thanks for reading.

**Comment by skyarkhangel** [comment]
1) I'm not a fan of Anime style. Rimworld not a fantasy game.
2) Hardcore SK already have tons of armors, weapons, own more then 15 factions for all tastes.
Rimarsenal its a simple Korean-fantasy style mod fo vanilla, which never be compatible with Combat Realism and NEVER in Hardcore SK.

**Comment by SmokeyUnicycle** [comment]
I also dislike the anime style, but I think the weapons themselves don't look very anime in game. The newer models are less ugly than the original ones and are pretty close to the future weapons already in game. Take a look at the guns the Scyther Mechanoid has in hardcore SK and these would fit right in. 

Rimsenal armor is pretty anime and is not very special, there are many late game armors in your mod already. 

Factions also not needed at all, we have many good factions already. 

I don't think either of those would be good to add in,. 

But, there are **not** many late game weapons and I don't think these are obviously too anime to fit in with the few future guns already in the mod. 

Everyone likes making real life guns and putting them in game, not many people are inventing future guns which is why we have so few I think :P 

If you don't think these fit that's fair, thanks for explaining your thinking.

**Comment by Owlchemist** [comment]
I agree, Rimsenal may be a bit too stylized for HCSK. Though I might suggest LewisDTC's Weapons (https://ludeon.com/forums/index.php?topic=27608.0).

In HCSK, you basically make this huge technology leap from tribal tools to a huge, if not overwhelming variety of modern guns. But DTC's weapons have a smooth pacing.

That said, I can imagine it would be a large undertaking to take on such a project.

**Comment by zakhad** [comment]
I would love to see some blunderbuss or flintlock weaponry like advanced medieval or Renaissance period something to bridge the gap between bows/crossbows to suddenly semi automatics.

**Comment by Blothorn** [comment]
I agree, although I think it is a bit hard to do well. I had been thinking about a mod adding much more detail to tech progression--probably something like

Black powder (musket) -> rifling (muzzle-loading long rifle) -> Minié ball (~Springfield 1861) -> repeaters/revolvers -> smokeless powder (Lee-Enfield).

That compacts quite a lot of history into the "musket"--early handguns to the decline of the muzzle-loading smoothbore covers around 400 years, and the rest of the tech tree only ~150. But there is not a lot of relevant variety there--perhaps split the matchlock from the faster-loading but less accurate flintlock.

The problem is viability of the early designs in the presence of melee. Muskets were a substantial regression from bows by all major ballistic measures: a skilled archer is more accurate than a skilled musketeer and can fire far faster. I think the main motivation for the move to muskets was that they are far less dependent on skill, with more straightforward ergonomics and a flat trajectory to effective range (which could be modeled in the CR framework by giving bows lower spreads but far higher sways, and the reverse to muskets). But even in the real world muskets were not viable on their own until the advent of the bayonet, and I imagine the same would be true in Rimworld (and it is not, to my knowledge, possible to make a combination ranged/melee weapon).

The situation is likely the same for the other muzzle-loaders--they would outperform bows but still stand little chance of stopping a charge due to long reloads and poor stopping power. Probably the first truly viable weapon would be a repeater--and while a Spencer or Winchester would be cool to have, I do not think it would do much to bridge the gap. Perhaps better would be to just split the existing tier 1, making the 19th-century revolvers and bolt-action rifles the first tier of firearms and moving everything else up a tier.

**Comment by Rhyssia** [comment]
Believe this is resolved
