### ISSUE TITLE
plunderers event broken

### ISSUE THREAD

**Issue by k4iser88** [skyarkhangel/Hardcore-SK#562]
The **''plunderers''** event spawns a group of antis, they just wander the map scaring colonists and eating animals.

-The creatures are almost unhittable with ranged weapons
-NPCs will attack them with the result of wasting all of their ammo on them and then melee suicide ( An entire trader caravan attacked one antis, 4 men shooting completely shred the caravan muffaloes and comrades from friendly fire, the survivors then went die on the antis bare handed when ammo finished. 4 men died + 3 muffaloes dead leaving the entire caravan supplies on the ground 10-20k loot... **antis survived** )

Tbh i don't think this is the way the event is supposed to work, they can just be ignored and occasionaly exploited to loot an entire guarded caravan doing nothing :)

**Comment by SmokeyUnicycle** [comment]
It's very annoying that they spawn Antis, because you cannot give a hunt command, and unlike raiders they will just hang out in the wilderness eating animals until they suddenly decide to ambush someone who goes out to chop wood or something an hour after the event happened and all the other ones (who you thought were all of them) are dead. 

You can't just select all of them when they spawn and click "hunt" and know they will be dealt with eventually. (There's no option) 

Meaning you have to micromanage a drafted team into hunting them down all over the map which is just kind of a pain in the ass. 


That's ignoring the fact that they're man eating bugs that don't steal anything like the description says and that some people are reporting them to be unshootable. I'm just killing everything with the hilariously OP T-1000s with sledghammers  so I wouldn't know
