### ISSUE TITLE
Several Issues regarding drugs and Raids/Sieges

### ISSUE THREAD

**Issue by TobWalter** [skyarkhangel/Hardcore-SK#729]
So I recently started a new colony with the intent to use drugs as my primary income source and I ran into the problem that there is no place to roll smokeleaves into joints. 'Production I' research states that colonists are now able to understant the use of weed etc. The smokeleaf plant itself states that a crafting spot is need to roll joint,  which is not buildable in HSK. Neither the Druglab nor the unlocked crafting stations from 'Production I' are able to 'craft' joints or use smokeleaf in general.

Raids in general happen a bit late IMO and do not represent the usual powercurve from vanilla Rimworld (Beginning with 1 Raider with a meele weapon and so on). I had several colonies (played on Cassandra classic on rough difficulty) now where Raids started to occur only after 1 or 2 years but then they do with 4 to 7 Raiders all equipped with Rifles and/or pistols which is impossible to defend if you only have your starting pistol/Rifle.

Sieges seem to be broken at the moment, Raider don't receive their equipment like cloth for sandbags and mortars. They just stand there and do nothing.

Also I recall in earlier versions you were able to use the 'smelt metal from weapons' at the weapon crafting bench using unwanted rifles/pistols. This is also no longer the case. Intended ?

**Comment by Lukavy** [comment]
1) You can make joints at the primitive weapon bench (or whatever it is called) where you make bows and arrows. I know, counterintuitive, however it makes sense.
2) I play on Randy Rough - I got like 6 raids and 3 infestation in one year. The first raid was 2 norbals with clubs. The strength of the raids depends on the wealth of your colony, as far as I remember, meaning instead of stockpiling gold - buy/make some weapon or die. Honestly I had no broblem killing 4 cat people with smgs using just bows, cower and brains. 
3) I got a siege as one of the raids the first year - everything works well.
4) You still can using both the primitive bench from #1 or arms bench.

**Comment by SoccaTheScrub** [comment]
A bit counter-intuitive but i accept it. 

Sieges in my game yet still have the same problem, got another siege tonight, still they dont receive their materials.
![20170206182929_1](https://cloud.githubusercontent.com/assets/17920494/22658507/a2337a90-ec9a-11e6-9f8f-fa2c39ec544a.jpg)

**Comment by Dunkhan** [comment]
I am having the same issue, my version is about 4 days old.

**Comment by Rhyssia** [comment]
Sieges are *fixed* now (They just throw an error when raiders try to aim off the map)
