### ISSUE TITLE
Leather and meat overhaul suggestion

### ISSUE THREAD

**Issue by Lukavy** [skyarkhangel/Hardcore-SK#744]
While I totally agree to the idea to simplify the meat, since it's basically all the same and there is absolutely no need for a hundred of different types, I have a suggestion to add 5th type of meat - fish.

As for leather, while there is certainly a need to get rid of 60+ different leathers I still think it is important to not oversimplify it. Right now almost all leathers in game are different! I hope many will agree that just 3-4 types of leather would greatly limit the options for the player. I mean it's not only about how thick the leather is; if I survive in desert - I look for leather to insulate heat well, if I build a bed - I look at the best leathers for the rest, if I build hospital bed - I look for the best bonus to the immunity, etc. And after all, I like to see my colonist wear a jacket made out of that bear he killed with his fists; it would be disappointing to see him in "hard leather jacket" instead! Plus, in reality say crocodile leather is very different from the bear leather! So my suggestion is to group the leathers for similar animals, say make snake and lacosdile have "reptile leather" and not just generic "common" or "hard" leather; make panda, grizzly bear and polar bear have "bear leather", etc. This way there still will be enough diversity and choices, while reducing the number of types of leathers by 50-80% to a manageable level.

**Comment by Owlchemist** [comment]
Adding more leathers would help add more granularity to whatever stats you're aiming for. That's something we could consider as play testing is done. Consider this first version of the overhaul a "starting point".

**Comment by Rhyssia** [comment]
Ok to close? (If no more comments by Sunday, closing.)

**Comment by zachary-foster** [comment]
Would it be possible to add a filter to the tailoring bench that allows making clothing from mixtures of leather? The clothing made from mixtures of leather could have average-to-weak stats compared to clothing made from a pure leather and just be called e.g. "leather jacket". It could also take longer to make. Either way, colonists would have to make multiple trips to the stockpile and back, which takes time. The weaker stats and longer manufacture time could compensate for the added convenience of being able to make things out of mixed leather. This would be especially valuable early in the game and later in the game the user could disallow mixed leather to take advantage of better stats and faster manufacture time. That way the 60+ leathers are not as much of a problem and I can still have my rat leather jacket.

Also more realistic; if you are going to freeze next winter without a parka, but you don't have enough of any one type of leather to make one, then you would work with what you had and patch things together rather than freeze.
