### ISSUE TITLE
Palettes and skips don't handle stacking graphics correctly

### ISSUE THREAD

**Issue by Owlchemist** [skyarkhangel/Hardcore-SK#759]
Some resources have a stacking graphic (texture _A is shown when there's only 1 item in a stack, texture _B when there's more than 1, and texture _C when the stack is full).

However, palettes and skips don't process this correctly. Once the stack moves beyond the original stack value, it just stays locked on the _B graphic. And for some reason it also looks like it's rendered a little smaller too.

**Comment by Lukavy** [comment]
Plus, the rotation doesn't fully work: it always takes from the bottom/left and stacks at the top/right. Also, it took me a while to figure out how exactly it works and why I need one instead of the regular stockpile-zone and what is the difference; there is no info on it anywhere even in internets, so maybe it's worth including some brief info into the description?
