### ISSUE TITLE
UI/Menus disappear, stuck in infinite loop.

### ISSUE THREAD

**Issue by betoxtreme** [skyarkhangel/Hardcore-SK#810]
## Description
Hi, I realized that the UI disappears and doesn't reappear after loading a specific save more than once.

After the first load, everything seems normal, there are no errors in the log, only some warnings about missing objects.

## Steps to reproduce

1. Start game (with HCSK 5.0)
2. Load provided save file (in appendix) , everything seems normal.
3. Reload the same save file without shutting down the game. Notice how **the UI disappears**.

## Possible causes

Unfortunately I don't know what causes this behavior but I've got a feeling that it all started with the Terminator join-event

This is the log output I copied in-game that loops;
```
Object reference not set to an instance of an object
  at ColonistBarKF.PSI.PSI.DrawColonistIcons (Verse.Pawn colonist, Boolean psi, Single rectAlpha, Rect rect) [0x00000] in <filename unknown>:0 
  at ColonistBarKF.ColonistBar_KF.ColonistBarOnGUI () [0x00000] in <filename unknown>:0 
  at RimWorld.MapInterface.MapInterfaceOnGUI_BeforeMainTabs () [0x00000] in <filename unknown>:0 
  at RimWorld.UIRoot_Play.UIRootOnGUI () [0x00000] in <filename unknown>:0 
  at Verse.Root.OnGUI () [0x00000] in <filename unknown>:0 
```

## Appendix

[log-file](https://gist.github.com/HugsLibRecordKeeper/03cd088c40d66bf86d785a192da183df) (complete log-output)
[save-file](https://gist.github.com/betoxtreme/a939b3207abf2a33cd4f2ca70da5e94b)

**Comment by skyarkhangel** [comment]
Then I suggest to play without ColonistBarKF.

**Comment by StopGamer** [comment]
Same issue

**Comment by Dunkhan** [comment]
I had the same issue but the message referred to the Moody UI

**Comment by Dunkhan** [comment]
Ok I just loaded the previous save, where the cold snap was still in progress. This save repeated the problem with the farm plots, and when I saved and loaded the map failed to load again.

Sucks for me because now I have to load an even earlier save and lose even more progress.

Good for the devs though, as it means this bug can be reproduced at will. 
To reproduce the symptoms I am getting with the attached save game:

1. Load the game
2. Wait until the cold snap ends
3. Observe that nothing can be planted on the farm plots
4. Save the game
5. Load the game
6. Observe that the load process hangs forever, and that and endlessly repeating message is in the log file.

I apologise that my game is not up to date with the current version, it is about 3 weeks old.
If the save can not be loaded in the current version I can zip and send my whole game folder if needed, please let me know.
[Autosave-2.zip](https://github.com/skyarkhangel/Hardcore-SK/files/809231/Autosave-2.zip)

**Comment by Vandenberg** [comment]
Thanks for the workaround, I have the same problem, I'm going to try it.
