### ISSUE TITLE
Tomato in "Fruit II" research

### ISSUE THREAD

**Issue by XPiriTorig** [skyarkhangel/Hardcore-SK#821]
Tomato in "Fruit II" research. Tomato - vegetable.

**Comment by Inei** [comment]
https://en.wikipedia.org/wiki/Tomato

**Comment by XPiriTorig** [comment]
I mean the everyday reality where a tomato is a vegetable. Oh yeah I'm from Russia)

**Comment by Dunkhan** [comment]
I love this issue report so much, the long winded reply from an actual botanist is delightful.

There is a saying:
"Intelligence is knowing a tomato is a fruit, wisdom is knowing not to put it in a fruit salad"

This also sums up the issue here. If tomato is classified as a fruit we have recipes like tomato juice (ok) and tomato fruit yoghurt (less ok), and on the other side we cant make a meal with tomato and meat (not ok at all).

**Comment by zachary-foster** [comment]
Although I agree with @Inei on the the fruit vs vegetable issue, in terms of simulating technological advancement, Im not sure the technical definitions matter as much. If someone is learning to garden, especially for subsistence purposes, they will not learn how to make all fruits first and then all vegetables or visa versa, etc, they will do what is easy and productive first (e.g. potato) and then the harder or less necessary things later. The climate will also determine what they grow. The growth form will also matter: knowing how to plant one type of tree would help you learn how to plant others. Same for grains.  

I wonder if it would make more sense to eliminate the fruit/vegetable distinction and replace it with more research ranks? Or maybe annuals vs perennials? Or group by growth form (annual forbs (e.g. lettuce, pumpkin, tomato), vines (e.g. beans, hops), roots (potato, carrot), perennial bushes (e.g. berries), trees? Im not sure how this would influence the recipe issues raised by @Dunkhan. 

I am relatively new to this mod pack, but I already cant play rimworld without it and I would like to contribute to it if I can. Sorry if my comments don't take into consideration the details of how the game is implemented.

**Comment by Dunkhan** [comment]
To clarify the situation, currently we have the following food categories for cooking (only vegetarian listed):

basic food (staples like rice and corn)
Extra food (some non staple vegetables)
Fruit

These categories are not connected to the research categories at all. Tomato is in fact listed under extra food currently, meaning it is researched as a fruit but in cooking it can not be used for juice or yoghurt, and it can be used for meat recipes. I did not realise this in my previous post.

The issue here therefore is purely about someone wanting to research tomatos, and not finding them in the expected research nodes. I think the current situation is correct despite the fact that it may confuse many people.

**Comment by Inei** [comment]
I actually thought of it as if we are using scientific approach in here since we are speaking of science - as we researching certain category of plants with certain scientific classification, and it's not if scientists are putting good effort to just do some serious investigation about what will taste better in the salad.
