### ISSUE TITLE
Found several errors ....

### ISSUE THREAD

**Issue by Azgat** [skyarkhangel/Hardcore-SK#859]
Sorry for my English.
1.  Only one mine extractor works. The rest extractors are standing.  Maybe I'm doing something wrong?
2, Why the terminator is washed?
3, Errors at the second speed. Only at the second speed. In the log file "Exception drawing Richard: System.IndexOutOfRangeException: Array index is out of range."
4, The oil field should disappear after production?
5, Domestication is not possible, since the inventory is complete. Is it a bug of the game or mods?
6, The position and size of the minimap are not saved after loading.
[output_log.txt](https://github.com/skyarkhangel/Hardcore-SK/files/908074/output_log.txt)

**Comment by sidfu** [comment]
2  terminatior is considered human like is why they have same needs.
3. i have no error at any speed so its probaly something else causeinng it. since its says a specifc person its probaly somethign else
5. thats not a bug their inventory is full drop some stuff or use animal food.
mini map is a seprate mod so best to report any issues on its forum. also check if it has a update.

**Comment by MrSamsa** [comment]
I notice that if you cut the power to the mining extractors while they are in the middle of the return-from-ground animation they will get stuck and never drop back down unless you rebuild them.

Easy to happen since they are power hungry and you would want to manage them eh?
